version: '3.8'
services:
  lakelandcup_auth_service_pg:
    image: postgres:14-alpine
    container_name: lakelandcup_auth_service_pg
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      interval: 120ms
      retries: 5
      start_period: 60ms
      timeout: 60ms
    env_file:
      - .dev.env
    ports:
      - 50002:5432
    volumes:
      - lakelandcup_auth_service_data:/var/lib/postgresql/data
    networks:
      - lakelandcup_backend
volumes:
  lakelandcup_auth_service_data:
networks:
  lakelandcup_backend: